name: integration-matter

services:
  redis:
    ports: 
      - 6379:6379
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
  driver:
    image: integration-matter
    build: ./
    restart: unless-stopped
    network_mode: host # Required for network discovery and magic packets
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - UC_CONFIG_HOME=/app/config
      - UC_DATA_HOME=/app/data
      - UC_INTEGRATION_INTERFACE=172.17.2.12
      - UC_INTEGRATION_HTTP_PORT=9988
      - UC_DISABLE_MDNS_PUBLISH=false
      - MATTER_STORAGE=redis://127.0.0.1:6379
    depends_on:
      - redis
